### ISSUE TITLE
Error when included recipe performs similar search

### ISSUE THREAD

**Issue by daharon** [sethvargo/chefspec#226]
I have a recipe which includes a second recipe, and both recipes perform a search on a specific data bag.  The data bag remains the same across the recipes, but the search parameter changes.

Each recipe has a spec file, and each spec file includes a search stub for the appropriate search.  

The problem is that when running rspec, I get an error complaining that :search was run with unexpected arguments.

Below is an example:

The base recipe:

``` ruby
# first_default.rb
include_recipe 'second::default'
items = search(:test_data_bag, 'data:abc')
items.each do |item|
  log item.to_s
end
```

The base spec file:

``` ruby
# first_default_spec.rb
require 'chefspec'

describe 'first::default' do
  let(:chef_run) { ChefSpec::ChefRunner.new(:log_level => :debug).converge 'first::default' }

  before(:each) do
    Chef::Recipe.any_instance.stub(:search).with(:test_data_bag, 'data:abc').and_return([{'data' => 'abc'}])
    chef_run = ChefSpec::ChefRunner.new(:log_level => :debug)
    chef_run.converge 'first::default'
  end

  it 'should log the test_data_bag data' do
    expect(chef_run).to log '{"data"=>"abc"}'
  end
end
```

The second recipe:

``` ruby
# second_default.rb
items = search(:test_data_bag, 'data:xyz')
items.each do |item|
  log item.to_s
end
```

The second spec file:

``` ruby
# second_default_spec.rb
require 'chefspec'

describe 'second::default' do
  let(:chef_run) { ChefSpec::ChefRunner.new(:log_level => :debug).converge 'second::default' }

  before(:each) do
    Chef::Recipe.any_instance.stub(:search).with(:test_data_bag, 'data:xyz').and_return([{'data' => 'xyz'}])
    chef_run = ChefSpec::ChefRunner.new(:log_level => :debug)
    chef_run.converge 'second::default'
  end

  it 'should log the test_data_bag data' do
    expect(chef_run).to log '{"data"=>"xyz"}'
  end
end
```

When I run rspec, I get the following error:

```
Failures:

  1) first::default should log the test_data_bag data
     Failure/Error: chef_run.converge 'first::default'
       #<Chef::Recipe:0x00000002a87c10> received :search with unexpected arguments
         expected: (:test_data_bag, "data:abc")
              got: (:test_data_bag, "data:xyz")
        Please stub a default value first if message might be received with other args as well. 
```

All my messing around just leads me to issue #63.
How can I stub these searches so that my test of first::default doesn't fail?
