### ISSUE TITLE
Receiving Failure/Error on default chefspec when using Docker driver

### ISSUE THREAD

**Issue by asciifaceman** [sethvargo/chefspec#627]
The chefspec is the default one:

```

require 'spec_helper'

describe 'sce-vmware-provisioning::default' do
  context 'When all attributes are default, on an unspecified platform' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end
  end
end
```

And I am currently using the Docker driver:

```
---
driver:
  name: docker
  binary: /usr/bin/docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.1

suites:
  - name: default
    run_list:
      - recipe[sce-vmware-provisioning::default]
    attributes:
```

however upon raking it, 

```
bundle exec rspec --color --format progress
.F

Failures:

  1) sce-vmware-provisioning::default When all attributes are default, on an unspecified platform converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error
       expected no Exception, got #<Errno::EACCES: Permission denied @ rb_sysopen - /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai/platforms/debian/8.1.json> with backtrace:
         # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'

```

I feel like it is trying to do something else?
